# Generated by Django 5.1 on 2024-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta')),
                ('respondido_em', models.DateField(blank=True, verbose_name='respondido em')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ('-enviado_em', '-respondido_em'),
            },
        ),
    ]
