# Generated by Django 5.1 on 2024-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='respondido_em',
            field=models.DateTimeField(blank=True, verbose_name='respondido em'),
        ),
    ]
